site_name: HujanIO
docs_dir: docs
theme :
  name: material
  palette :
    primary: teal
    accent: light blue
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
  custom_dir: material
nav:
  - Hujan UI : index.md
  - Getting Started :
      - Prerequisite: prerequisite.md
      - MAAS Installation: install-maas.md
      - Deploy Hujan UI : install.md