# name: Build Mkdocs

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-python@v2
#       with :
#         python-version: 3.x
#     - name: Install Dependency
#       run: pip install -r requirements.txt
#     - name: Build the Mkdocs
#       run: mkdocs gh-deploy --force